driver:
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        x: toggleManualShoot
        a: autoBalance
    axes:
        leftTrigger: brakeMode
        rightTrigger: slowMode
    buttons:
        leftBumper: autoBalance
        rightBumper: toggleCollectorReverse
        start: zeroPose
operator:
    rumble: false
    joysticks:
        left:
            horizontal: manualTurretXVal
            vertical: manualTurretYVal
        right:
            vertical: manualClimberArm
    dpad:
        up: raiseBucket
        down: lowerBucket
        left: turretJogLeft
        right: turretJogRight
    buttonpad:
        x: toggleCamera
        y: autoClimb
        a: toggleTurretMode
        b: eject
    axes:
        leftTrigger: yeetShot
        rightTrigger: shoot
    buttons:
        start: toggleTopClamp
        back: toggleBottomClamp
demoMode: false
