driver:
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        x: toggleManualShoot
        y: unlockClimber
    axes:
        leftTrigger: brakeMode
        rightTrigger: slowMode
    buttons:
        leftBumper: toggleCollector
        rightBumper: toggleCollectorReverse
        start: zeroPose
operator:
    rumble: false
    joysticks:
        left:
            horizontal: manualTurretXVal
            vertical: manualTurretYVal
        right:
            vertical: manualClimberArm
    dpad:
        up: raiseBucket
        down: lowerBucket
        left: turretJogLeft
        right: turretJogRight
    buttonpad:
        x: toggleCamera
        y: autoClimb
        a: toggleTurretMode
        b: eject
    axes:
        leftTrigger: yeetShot
        rightTrigger: shoot
    buttons:
        start: toggleTopClamp
        back: toggleBottomClamp
buttonboard:
    upLeft: empty
    up: empty
    upRight: empty
    left: empty
    center: empty
    right: empty
    downLeft: empty
    down: empty
    downRight: empty
demoMode: false

