driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    axes:
        leftTrigger: yeetShot
        rightTrigger: slowMode
    dpad:
        left: turretJogLeft
        right: turretJogRight
    buttons:
        leftBumper: toggleCollector
        rightBumper: toggleCollectorReverse
        start: zeroPose
operator:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: manualTurretXVal
            vertical: manualTurretYVal
        right:
            vertical: manualClimberArm
    dpad:
        up: raiseBucket
        down: lowerBucket
    buttonpad:
        y: autoClimb
    buttons:
        leftBumper: autoAim
        rightBumper: toggleHood
        start: toggleTopClamp
        back: toggleBottomClamp
mrbuttons:
    rumble: false
    dpad:
        up: up_function
        down: down_function
        left: left_function
        right: right_function
    buttonpad:
        a: a_function
        b: b_function
        x: x_function
        y: y_function
    buttons:
        leftBumper: leftBump_function
        rightBumper: rightBump_function
        start: start_function
        back: back_function



